# -- init.lua --
require("mynvim.plugins-setup")
require("mynvim.core.options")
require("mynvim.core.keymaps")
require("mynvim.core.colorscheme")
require("mynvim.plugins.comment")
require("mynvim.plugins.nvim-tree")
require("mynvim.plugins.lualine")
require("mynvim.plugins.telescope")
require("mynvim.plugins.nvim-cmp")
require("mynvim.plugins.lsp.mason")
require("mynvim.plugins.lsp.lspconfig")
require("mynvim.plugins.autopairs")
require("mynvim.plugins.treesitter")
require("mynvim.plugins.gitsigns")
require("mynvim.plugins.lsp.null-ls")
